FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env

# Build solution
WORKDIR /src
COPY src/ .
RUN dotnet publish -c Release -o /publish /src/EventPublisherApi/EventPublisherApi.csproj

# Install dotnet debug tools
#RUN dotnet tool install --tool-path /tools dotnet-trace \
# && dotnet tool install --tool-path /tools dotnet-counters \
# && dotnet tool install --tool-path /tools dotnet-dump \
# && dotnet tool install --tool-path /tools dotnet-gcdump

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime

# Copy dotnet-tools
#WORKDIR /tools
#COPY --from=build-env /tools .

# Copy app
WORKDIR /publish
COPY --from=build-env /publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "EventPublisherApi.dll"]