FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /src
COPY src/ .
RUN dotnet publish -c Release -o /publish /src/EventPublisherApi/EventPublisherApi.csproj

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "EventPublisherApi.dll"]